name: cron
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master

concurrency:
  group: vcard
  cancel-in-progress: true

jobs:
  vcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Run Unit Tests
        run: |
          python3 test.py
        env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: "${{secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS}}"
          GOOGLE_SPREADSHEET_ID: "${{secrets.GOOGLE_SPREADSHEET_ID}}"

      - name: Run Sync
        env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: "${{secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS}}"
          GOOGLE_SPREADSHEET_ID: "${{secrets.GOOGLE_SPREADSHEET_ID}}"
        run: |
          python3 main.py

